name: Type Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ty:
    name: Run ty
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          python-version: "3.12"
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Sync project dependencies
        run: uv sync --frozen

      - name: Type check with ty
        run: uv run --frozen --with ty ty check
