name: Type Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ty:
    name: Run ty
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Sync project dependencies
        run: uv sync --frozen

      - name: Type check with ty
        run: uv run --frozen --with ty ty check
